// generated by yarn generate:webp
import src600w from '~/assets/images/page_header@600w.webp';
import src960w from '~/assets/images/page_header@960w.webp';
import src1280w from '~/assets/images/page_header@1280w.webp';
import src1920w from '~/assets/images/page_header@1920w.webp';

const images = {
  src600w,
  src1920w,
  src960w,
  src1280w,
  aspectRatio: 3.1133671742808797,
};

export default images;
