// generated by yarn generate:webp
import src960w from '~/assets/images/press_header@960w.webp';
import src600w from '~/assets/images/press_header@600w.webp';
import src1280w from '~/assets/images/press_header@1280w.webp';
import src1920w from '~/assets/images/press_header@1920w.webp';

const images = {
  src960w,
  src600w,
  src1280w,
  src1920w,
  aspectRatio: 2.244668911335578,
};

export default images;
