// generated by yarn generate:webp
import src600w from '~/assets/images/footer@600w.webp';
import src960w from '~/assets/images/footer@960w.webp';
import src1280w from '~/assets/images/footer@1280w.webp';
import src1920w from '~/assets/images/footer@1920w.webp';

const images = {
  src1280w,
  src960w,
  src600w,
  src1920w,
  aspectRatio: 1.5985096870342772,
};

export default images;
