// generated by yarn generate:webp
import src600w from '~/assets/images/solutions/mentor@600w.webp';
import src960w from '~/assets/images/solutions/mentor@960w.webp';
import src1280w from '~/assets/images/solutions/mentor@1280w.webp';
import src1920w from '~/assets/images/solutions/mentor@1920w.webp';

const images = {
  src1280w,
  src1920w,
  src600w,
  src960w,
  aspectRatio: 1.4992458521870287,
};

export default images;
