// generated by yarn generate:webp
import src600w from '~/assets/images/solutions/bpm@600w.webp';
import src960w from '~/assets/images/solutions/bpm@960w.webp';
import src1280w from '~/assets/images/solutions/bpm@1280w.webp';
import src1920w from '~/assets/images/solutions/bpm@1920w.webp';

const images = {
  src960w,
  src600w,
  src1920w,
  src1280w,
  aspectRatio: 1.5,
};

export default images;
