// generated by yarn generate:webp
import src600w from '~/assets/images/solutions/development@600w.webp';
import src960w from '~/assets/images/solutions/development@960w.webp';
import src1280w from '~/assets/images/solutions/development@1280w.webp';
import src1920w from '~/assets/images/solutions/development@1920w.webp';

const images = {
  src600w,
  src1920w,
  src960w,
  src1280w,
  aspectRatio: 2.125,
};

export default images;
