// generated by yarn generate:webp
import src600w from '~/assets/images/solutions/infra@600w.webp';
import src960w from '~/assets/images/solutions/infra@960w.webp';
import src1280w from '~/assets/images/solutions/infra@1280w.webp';
import src1920w from '~/assets/images/solutions/infra@1920w.webp';

const images = {
  src960w,
  src600w,
  src1920w,
  src1280w,
  aspectRatio: 1.6193619361936193,
};

export default images;
